export const USER_ROUTERS = 'USER_ROUTERS'
export const SAVE_USERPOWERINFO = 'SAVE_USERPOWERINFO'
export const USER_BASICUROUTERS = 'USER_BASICUROUTERS'
export const TOGGLE_PAGESIDE = 'TOGGLE_PAGESIDE'
TOGGLE_PAGESIDE